### ISSUE TITLE
ISO BMFF Byte Stream Format spec does not mention emsg

### ISSUE THREAD

**Issue by chrisn** [w3c/me-media-timed-events#1]
A question was raised during the [IG teleconference on 5 June 2018](https://www.w3.org/2018/06/05-me-minutes.html), whether the [ISO BMFF Byte Stream Format](https://www.w3.org/TR/mse-byte-stream-format-isobmff/) spec would require updating to enable support for `emsg` events (via a `DataCue` or similar API).

**Comment by timse7** [comment]
emsg is defined in ISO/IEC 23009-1:2014 (DASH), 5.10.3.3

**Comment by johnsim** [comment]
My understanding - the scope of the ISO BMFF Byte Stream Format spec is to be used by the Media Source Extensions spec, and that the scope of the Media Source Extensions [https://www.w3.org/TR/media-source](url) spec is the dynamic construction of media streams for <audio> and <video>. Exposing emsg events to JavaScript Apps is out of scope for the Media Source Extensions (DataCue? Other?). And based because it is scoped to use by the MSE spec, emsg is also out of scope for the Byte Stream spec. Thoughts?

**Comment by gmandyam** [comment]
Unfortunately the W3C bytstream spec only refers to http://standards.iso.org/ittf/PubliclyAvailableStandards/c068960_ISO_IEC_14496-12_2015.zip, which has no mention of emsg.  Therefore in my interpretation, an implementation can be compliant with the W3C ISO BMFF spec and completely disregard the emsg box.

At very least, the bytestream specification should be updated to speciify the desired emsg processing.

**Comment by chrisn** [comment]
The other related spec we should review is [Sourcing In-band Media Resource Tracks from Media Containers into HTML](https://dev.w3.org/html5/html-sourcing-inband-tracks/). Although focused on text tracks, this is perhaps also relevant for emsg.

**Comment by johnsim** [comment]
If I am correct about its scope, the bytestream spec should *not* be updated to specify emsg processing.

**Comment by johnsim** [comment]
@gmandyam 
I agree that as defined, an emsg box is part of a media segment; but that does not imply that everything found in a media segment is in scope for the media source extensions spec or the byte stream format spec. 

MSE scope is the dynamic construction of media streams for audio and video. The Byte Stream Format Spec is listed in the MSE registry - which is (from title of registry and stated purpose) "... intended to enhance interoperability among implementations and users of SourceBuffer objects described in the Media Source Extensions (MSE) specification."

Processing of emsg boxes will be described in some other W3C spec - perhaps DataCue? I do not see it being described in MSE and therefore I don't see it belonging in the byte stream format spec.

**Comment by boblund** [comment]
MSE media specs describe requirements for the media container insofar as required for MSE to process it. It's not apparent emsg has any requirements in this regard, but maybe.

"Sourcing In-band Media Resource Tracks from Media Containers into HTML" [1]  was created to define how the contents of various media containers should be recognized by the user agent and how the user agent makes this media container content available to web apps via various APIs. [1] is referenced by the HTML and MSE specs.

Supporting emsg will require extending [1] to define where the UA should recognize emsgs, in all the relevant media containers, and the common API to make the contents available. For emsgs destined to JavaScript, the API definition will need to reference (or define) some cue format - there are some options in this regard. DataCue is one. If the IG has requirements for emsg use cases beyond events to JavaScript, then something beyond the functionality of DataCue might be required.

[1] https://dev.w3.org/html5/html-sourcing-inband-tracks/

**Comment by chrisn** [comment]
Just a note that there's also an [open issue](https://github.com/w3c/media-source/issues/174) against the MSE spec for this question.

**Comment by chrisn** [comment]
I'll close this issue and invite anyone interested to follow up the discussion in the [DataCue GitHub repository][1]. The [explainer][2] currently suggests updating "Sourcing In-band Media Resource Tracks from Media Containers into HTML", either in its current form, or by splitting it into new set of format-specific specs.

[1]: https://github.com/WICG/datacue
[2]: https://github.com/WICG/datacue/blob/5447243499ed5a1f975968f72a6d1316fd243973/explainer.md#in-band-timed-metadata-processing
