### ISSUE TITLE
Describe VTTCue approach

### ISSUE THREAD

**Issue by chrisn** [w3c/me-media-timed-events#17]
The [`VTTCue` API](https://w3c.github.io/webvtt/#vttcue) can be used to carry timed metadata, typically by encoding the metadata as a JSON string. Add details of the pros and cons of this approach to the Gap analysis section of the use case and requirements document.

**Comment by gmandyam** [comment]
Addressed with https://github.com/w3c/me-media-timed-events/pull/19
