### ISSUE TITLE
Invite comments by filing issues

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/me-media-timed-events#28]
Invite people to make comments on the document by filing issues on this repo by:

* [x] Adding a link to the repo at the top
* [x] Changing the SoTD section that invites emails to invite people to file issue
* [ ] Add an issue template to the repo to guide commenters in how to construct an issue usefully.

**Comment by chrisn** [comment]
I think we can close this. Given the volume of discussion here, we don't really need an issue template.
