### ISSUE TITLE
Add description on DAInty to Sec. 3 of document

### ISSUE THREAD

**Issue by gmandyam** [w3c/me-media-timed-events#3]
https://w3c.github.io/me-media-timed-events/#related-industry-standards should include description of DASH-IF efforts to define event API for DASH Clients:  DASH Client APIs for Interactivity (DAInty)

**Comment by chrisn** [comment]
@gmandyam Please review and let me know if any changes are needed. Thanks!

**Comment by gmandyam** [comment]
Addressed by https://github.com/w3c/me-media-timed-events/pull/12
