### ISSUE TITLE
Add more drivers for better synchronisation

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/me-media-timed-events#36]
§3.4 currently mentions only video shot synchronisation as a driver for better synchronisation.

There's another big one, which is to reduce the chance of wide variance in required reading rate (words per minute) from the authored subtitles.

For a slightly edge case example, to demonstrate the point, say there are words coming in at 240 per minute, which are subtitles for a fast dialog program, i.e. one every quarter of a second on average. At this cadence, being 250ms late is 100% out of register. Yet guidelines such as the BBC's regarding [matching subtitle to speech onset](http://bbc.github.io/subtitle-guidelines/#Match-subtitle-to-speech-onset) note: 

> When two or more people are speaking, it is particularly important to keep in sync. Subtitles for new speakers must, as far as possible, come up as the new speaker starts to speak. Whether this is possible will depend on the action on screen and rate of speech.

With the synchronisation capability as currently specified, the possibility also depends on the user agent implementation, which is something in our gift to influence.

**Comment by nigelmegitt** [comment]
I recently learned that the Nordig (Nordic and Irish market) technical specifications for DVB receivers [[PDF]](https://nordig.org/wp-content/uploads/2018/10/NorDig-Unified-Requirements-ver.-3.1.pdf ) mandate that those receivers support TTML in MPEG-2 Transport Streams, using the DVB/ETSI specification ETSI EN 303 560, and direct HEVC receivers to display TTML in preference to DVB bitmap subtitles where both are available. 

The presentation timing precision is specified as being within 2 frames.

See pages 105-110 for details.

**Comment by chrisn** [comment]
See section 7.3.1 in the referenced document.
