### ISSUE TITLE
event is not defined

### ISSUE THREAD

**Issue by cconcolato** [w3c/me-media-timed-events#41]
The term `media timed event` is defined as
> metadata events synchronized to the media timeline of a media resource.

This definition is based on the word `event` which is not defined. Is it an [Event](https://www.w3.org/TR/dom41/#event) as defined in HTML? Or something else? 

Also the timing model for this event is not clear. Is an event instantaneous (i.e. specified by only one time in the media timeline) or long-running (with an end time on the media timeline)?
The use case sections says that an event can do both:
> Media timed events carry metadata that is related to points in time, or regions of time on the media timeline

Also section 6.3 says:
> when the current media playback position reaches the start time and the end time of a media timed event

**Comment by ingararntzen** [comment]
Chiming in with @cconcolato.

In my view *event* is not the correct term here. It seems like *cue* is a better name for an object that is tied to a point or a region on the timeline. In my view, the term *event* should be reserved for named js callbacks, e.g. *enter* or *exit* which occur when the cue becomes *active* or *inactive* during playback or timeshifting.

For reference, in the implementation of the the [sequencer](https://webtiming.github.io/timingsrc/doc/api_sequencer.html) for the [timingobject](https://webtiming.github.io/timingsrc/doc/api_timingobject.html) I define cue as an object with properties (key, interval, data). The *interval* defines a region on the timeline `(low, high)`. A point on the timeline is simply a special case of region, where both interval endpoints happens to be the same `low == high.

I've noticed this kind of terminology confusion also other contexts, e.g. *dash events*, which are basically objects with a timestamp as far as I've understood. I'd recommend trying to maintain a distinctions between *data/objects* and *events* (essentially referring to state transitions in *data/objects*)

**Comment by chrisn** [comment]
Thanks @cconcolato, @ingararntzen for your valuable feedback.

> Cyril: This definition is based on the word event which is not defined. Is it an Event as defined in HTML? Or something else?

I agree, we have some ambiguity here. DASH `emsg` is one of the motivations behind this work, but by "event" we're mainly talking about the DOM events triggered at cue start and end times, which we expect to be synchronized to media playback.

> Cyril: Also the timing model for this event is not clear. Is an event instantaneous (i.e. specified by only one time in the media timeline) or long-running (with an end time on the media timeline)?

I don't think we have use cases in this document for instantaneous events, so happy to drop this, all the examples have both start and end times. More on this below...

> Ingar: For reference, in the implementation of the the sequencer for the timingobject I define cue as an object with properties (key, interval, data). The interval defines a region on the timeline (low, high). A point on the timeline is simply a special case of region, where both interval endpoints happen to be the same low == high.

I agree. You can create an instantaneous (point) event by making a `TextTrackCue` with times equal to each other. In practice, I've found that these generate `onenter` and `onexit` events as expected, but there seems to be a minimum non-zero duration needed for the cues to appear in the `activeCues` list inside a `oncuechange` handler, and this duration differs between implementations.

At this stage, the only change to the timing model that we are proposing is to make the event triggering more accurate; something allowed by HTML but not mandated (see "time marches on").

**Comment by nigelmegitt** [comment]
> all the examples have both start and end times

It may not be related to instantaneous events, but I think there's one example where this isn't true: live subtitles/captions where the end time of the cue is not known when it is first authored, and some mechanism later sets the end time when it is known.

**Comment by chrisn** [comment]
Thanks, Nigel, this is another important case, also discussed in https://github.com/w3c/me-media-timed-events/issues/39. I'd like to resolve this issue by clarifying "event" terminology, then use #39 to capture the requirements around end times.

**Comment by mavgit** [comment]
>  In practice, I've found that these generate `onenter` and `onexit` events as expected, but there seems to be a minimum non-zero duration needed for the cues to appear in the `activeCues` list inside a `oncuechange` handler, and this duration differs between implementations.

This is important as it makes interoperability more difficult. It would seem to me that zero duration cues should be included in the `activeCues` list.

What's the best way to get this fixed? Is a recommendation to fix this variance between implementations included in this document? Or should it be handled outside this document, since maybe it's broader in scope?

**Comment by ingararntzen** [comment]
@mavgit. I agree. To not report enter/exit event as playback passes by is simply a bug and must be fixed.

**Comment by ingararntzen** [comment]
On second thought. I'm not so sure about this after all. The sequencer implementation (open source JS alternative to track elements) guarantees enter/exit events for cues with length 0, and guarantees that the active cues list is always consistent with the history of event callbacks from the sequencer. However, the sequencer will deliver all due events in a single batch, implying that the enter and exit events for length 0 cues will always be delivered together (in the right order - depending on playback direction). 

So, the cue will not be a part of the active cues lists (unless playback is paused on exactly this point).

Fixing this, would be possible (but complicated). I would still be reluctant to actually do this for the sequencer, as it might have performance implications for huge event batches. We have applications operating on datasets > 100K cues, and framerate reevaluation of large sets of active cues, which means that the batch oriented nature of the sequencer is crucial.

So from a theoretical point of view, I guess this may be a bug. From a practical point not so much?

**Comment by nigelmegitt** [comment]
If I've understood the active cue list correctly, whenever the event loop runs, any cue that has the same start and end time and that time is between the previous time the event loop ran and the current time (where time is playback position), will be added to the missed cues list and its `onenter` and `onexit` events will be fired _before_ the `cuechange` event on the text track. This is defined in https://html.spec.whatwg.org/multipage/media.html#time-marches-on

Additionally, I don't expect that any UA would run the event loop between that cue's `onenter` and `onexit` handlers so there's no opportunity for step 17 to capture such a cue in _current cues_ and set its active flag.

This is _why_ the cue is not in the active cues list, but doesn't explain if it's a good idea or not. I think it's probably unwise, in the event handlers of a cue C, to exclude C itself from the list of cues that are probably active, even if the text track active cue list does not include it. It's also unwise to use the Text Track's `cuechange` event to try to spot all events passing by.

@mavgit Is there a particular use case for wanting to see these cues in the active cue list at some particular playback time?

**Comment by mavgit** [comment]
> @mavgit Is there a particular use case for wanting to see these cues in the active cue list at some particular playback time?

No. My issue was addressing the browser interoperability issues in @chrisn comment https://github.com/w3c/me-media-timed-events/issues/41#issuecomment-487961057
> duration differs between implementations

**Comment by chrisn** [comment]
> @nigelmegitt If I've understood the active cue list correctly

I believe your understanding to be correct.

> @mavgit This is important as it makes interoperability more difficult

It does. We have text in the [Gap Analysis section](https://w3c.github.io/me-media-timed-events/#using-cues-to-track-progress-on-the-media-timeline) to describe current behaviour allowed by the HTML spec, which leaves room for variation between implementations.

[Here](https://w3c.github.io/me-media-timed-events/#synchronization) is the current recommendation we have. Is there anything we want to add or change, to either the recommendation or to the gap analysis?

**Comment by mavgit** [comment]
I don't understand the sentence with "that would allow to couple". It seems like a typo or a missing word to me… or maybe I'm just too tired to get it.

**Comment by nigelmegitt** [comment]
> I don't understand the sentence with "that would allow to couple"

You're right @mavgit that sentence doesn't work grammatically and needs a refactor.

**Comment by nigelmegitt** [comment]
> My issue was addressing the browser interoperability issue

@mavgit Ah I see, then the question is not "should zero duration cues appear in the active cue list?" but "what is the minimum duration of a cue to guarantee that it appears in the active cue list?", and the answer to that is almost certainly 250ms right now. Bringing down the synchronisation threshold to 20ms as proposed would presumably reduce it to 20ms.

But there's a bigger question, which is: what use case depends on cues being added to the active cue list reliably? If this reliability is a dependency for some code, it either needs to set the duration to be long enough, or be refactored to remove the dependency, by using cue events rather than text track cue list events.

**Comment by mavgit** [comment]
>  the question is not "should zero duration cues appear in the active cue list?" but "what is the minimum duration of a cue to guarantee that it appears in the active cue list?"

Yes, that was my question.

> Bringing down the synchronisation threshold to 20ms as proposed would presumably reduce it to 20ms.

Makes sense.

>  what use case depends on cues being added to the active cue list reliably?

I don't know off hand whether there is or isn't a use case that depends on this.

**Comment by chrisn** [comment]
PR #49 includes changes that I hope address the terminology issues mentioned here. Please comment there if further changes are needed.

The other topic discussed here is minimum cue duration required for a cue to appear in the `activeCues` list. This is affected by: how often _time marches on_ is run, the execution time of the JavaScript handler function.

> Is there a particular use case for wanting to see these cues in the active cue list at some particular playback time?

I think `emsg` events HbbTV would be one such case. Because this uses a native DASH player, the only mechanisms the web app has to receive the events are: use a `cuechange` handler, or poll `activeCues` from a rAF loop for higher timing precision. A rAF handler would be expensive particularly for TV devices.

The current specifed `cuechange` and `activeCues` behaviour seems correct to me. My hope is that we can develop a solution such that native DASH implementations can use cue `enter`/`exit` events rather than `cuechange` events.

**Comment by chrisn** [comment]
PR #49 has now been merged, so I will close this. Please review the [current draft][1] and raise issues if further changes are needed.

[1]: https://w3c.github.io/me-media-timed-events/
