### ISSUE TITLE
Add informative reference to HLS specification (DATERANGE, ID3-in-MPEG-2-TS)

### ISSUE THREAD

**Issue by jernoble** [w3c/me-media-timed-events#43]
HLS allows for delivery of timed metadata events, specifically using the [EXT-X-DATERANGE](https://tools.ietf.org/html/rfc8216#section-4.3.2.7) tag, as well delivery of [ID3](http://www.id3.org/id3v2.3.0) timed metadata carried in [MPEG-2 Transport Streams](https://www.iso.org/standard/62074.html).

Could an informative note mentioning HLS be added to the section 4. under "Related Industry specifications"?

**Comment by chrisn** [comment]
Thanks @jernoble, more than happy to add this.

**Comment by chrisn** [comment]
Resolved via https://github.com/w3c/me-media-timed-events/commit/388c126e620e3ad2440abc9ab7c49dd46d63c917, received LGTM from Jer by email.
