### ISSUE TITLE
Add more use cases for timed events

### ISSUE THREAD

**Issue by chrisn** [w3c/me-media-timed-events#6]
Action item from [2018-06-18 TF call](https://www.w3.org/2018/06/18-me-minutes.html):

Add more use cases for timed events to document, e.g., 3GPP service interactivity mentioned on the [2018-04-30 TF call](https://www.w3.org/2018/04/30-me-minutes.html).

**Comment by rjksmith** [comment]
Thanks for your invitation to introduce Web Video Map Tracks (WebVMT) to the Media Timed Events group yesterday. As promised, here are details of the two use cases I described.

  1. **Geolocation Map Presentation:** Metadata cues, synchronised with the timed media, can drive an online map, e.g. Google Maps, rendered in a separate HTML element alongside the media container on the web page. The media play head position controls presentation and animation of the map, e.g. pan and zoom, and allows annotation to be added and removed, e.g. a marker, at specified times during media playback. Control can also be overridden by the user with the usual interactive features of the map at any time, e.g. zoom. Concrete examples are provided by the [tech demos](http://webvmt.org/demos) at the WebVMT website.

  1. **Geolocation Rapid Indexing:** The VMT track file forms a location-time index of the media file allowing a video archive to be rapidly searched for a particular location, e.g. 'what is the most recent image of location x?' Searching a few kilobytes of VMT file is faster than searching megabytes of media file for metadata embedded within it. Only the VMT file need be parsed to identify whether the linked media file contains the target location and, if so, when - making the process faster and more efficient, which is important for online search engines. The [Area Survey](http://w3c.github.io/sdw/proposals/geotagging/webvmt/#areasurvey) use case in the WebVMT Editor's Note is an example of this.

Please let me know if you need further details.

**Comment by chrisn** [comment]
Closing, as the document references the 3GPP work item and WebVMT map presentation use case. The metadata search use case is included in the [DataCue explainer][1].

[1]: https://github.com/WICG/datacue/blob/master/explainer.md
