### ISSUE TITLE
Add timing accuracy requirements for subtitle rendering

### ISSUE THREAD

**Issue by chrisn** [w3c/me-media-timed-events#7]
Action item from [2018-06-18 TF call](https://www.w3.org/2018/06/18-me-minutes.html):

Following [IG discussion](https://github.com/w3c/media-and-entertainment/issues/4), add timing accuracy requirements for subtitle rendering.

**Comment by nigelmegitt** [comment]
I think it would also be useful to reference EBU-TT-D as per my https://github.com/w3c/media-and-entertainment/issues/4#issuecomment-397564406 .

**Comment by nigelmegitt** [comment]
I've added a note to the pull request suggesting that the BBC subtitle Guidelines section 6 is also referenced as well as section 5. That imposes tighter accuracy requirements, due to alignment with shots, which therefore need to be frame accurate (at least at 25 fps).

**Comment by chrisn** [comment]
I have updated the [pull request](https://github.com/w3c/me-media-timed-events/pull/9) based on Nigel's comments. @nigelmegitt, @gmandyam, will merge if this looks OK to you.

**Comment by gmandyam** [comment]
PR merged.  Closing issue.
